/**
 * Audit triggers, generated by us from the live schema.
 *
 * The author never writes one, so "a table was added and its trigger forgotten"
 * cannot happen — the coverage is structural rather than remembered. Each trigger
 * fires inside the same transaction as the change it records, so the audit cannot
 * drift from the world, and a rolled-back batch leaves no audit rows behind.
 */
import type { Database } from 'bun:sqlite';

/**
 * A leading underscore is RESERVED for us. Listing our tables by name meant every
 * new one had to be remembered here, and a forgotten entry would silently start
 * auditing our own bookkeeping.
 */
const isInternal = (name: string): boolean => name.startsWith('_');

const q = (s: string): string => `"${s.replace(/"/g, '""')}"`;

/** `json_object('a', new."a", 'b', new."b")` */
const snapshot = (alias: 'new' | 'old', cols: string[]): string =>
  `json_object(${cols.map((c) => `'${c}', ${alias}.${q(c)}`).join(', ')})`;

export function userTables(db: Database): string[] {
  const rows = db
    .query<{ name: string }, []>(
      `SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`
    )
    .all();
  return rows.map((r) => r.name).filter((n) => !isInternal(n));
}

export function installAuditTriggers(db: Database): string[] {
  const made: string[] = [];
  for (const table of userTables(db)) {
    const cols = db
      .query<{ name: string }, []>(`PRAGMA table_info(${q(table)})`)
      .all()
      .map((c) => c.name);
    if (cols.length === 0) continue;

    // Session, call and virtual time are read from tables we own, so a trigger can
    // attribute a row change to the call that caused it without any extension.
    const ctx =
      `(SELECT session FROM _context WHERE id = 1), ` +
      `(SELECT step FROM _context WHERE id = 1), ` +
      `(SELECT call FROM _context WHERE id = 1)`;
    const who = `(SELECT actor FROM _context WHERE id = 1)`;
    const at = `(SELECT now FROM _clock WHERE id = 1)`;
    const cols_ = `_audit(session, step, call, tbl, rowid_, op, before, after, actor, t_virtual)`;

    for (const [op, alias, before, after] of [
      ['INSERT', 'new', 'NULL', snapshot('new', cols)],
      ['UPDATE', 'new', snapshot('old', cols), snapshot('new', cols)],
      ['DELETE', 'old', snapshot('old', cols), 'NULL'],
    ] as const) {
      const name = `_audit_${table}_${op.toLowerCase()}`;
      db.run(
        `CREATE TRIGGER ${q(name)} AFTER ${op} ON ${q(table)} BEGIN
           INSERT INTO ${cols_}
           VALUES (${ctx}, '${table}', ${alias}.rowid, '${op}', ${before}, ${after}, ${who}, ${at});
         END;`
      );
      made.push(name);
    }
  }
  return made;
}
