#!/usr/bin/env bun
/**
 * Regenerate `src/nebius-models.ts` from what Nebius currently serves.
 *
 * The table is checked in rather than fetched at startup, for two reasons that
 * both matter more than freshness: a run must work with no network to a model
 * catalogue, and a price that changes between two runs of the same research
 * would make their costs incomparable without anyone noticing. Regenerating is
 * a deliberate act, and the diff is the record of what moved.
 *
 * `GET /v1/models?verbose=true` is undocumented but is the only machine-readable
 * source of Nebius pricing — the console's endpoints page is a browser app, and
 * the docs carry no per-model table at all. The plain `/v1/models` gives ids and
 * nothing else.
 *
 *   bun run scripts/nebius-catalog.ts            # rewrite the table
 *   bun run scripts/nebius-catalog.ts --check    # fail if it is out of date
 *
 * The key resolves the same way it does for a run: flag, env, keychain, .env.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { resolveKey } from '../src/keys.ts';
import { NEBIUS, NEBIUS_BASE_URL } from '../src/nebius.ts';

const OUT = resolve(import.meta.dir, '..', 'src', 'nebius-models.ts');

interface Verbose {
  id?: string;
  context_length?: number;
  architecture?: { modality?: string };
  pricing?: { prompt?: string; completion?: string };
  supported_features?: string[];
  regions?: Array<{ country_code?: string; name?: string }>;
}

/** Per-token USD, as a string, → per-million, as a number the file can carry. */
function perMTok(raw: string | undefined): number {
  const n = Number(raw ?? '0');
  if (!Number.isFinite(n)) throw new Error(`unparseable price "${raw}"`);
  // Six decimals is exact for every rate Nebius quotes and keeps the generated
  // file free of the 0.30000000000000004 that a naive ×1e6 produces.
  return Number((n * 1_000_000).toFixed(6));
}

function render(models: Verbose[], on: string): string {
  const rows = models
    .map((m) => {
      const features = m.supported_features ?? [];
      const region = (m.regions ?? [])
        .map((r) => `${r.name ?? '?'} (${r.country_code ?? '?'})`)
        .join(', ');
      return (
        `  {\n` +
        `    id: '${m.id}',\n` +
        `    inputPerMTok: ${perMTok(m.pricing?.prompt)},\n` +
        `    outputPerMTok: ${perMTok(m.pricing?.completion)},\n` +
        `    contextWindow: ${m.context_length ?? 0},\n` +
        `    reasoning: ${features.includes('reasoning')},\n` +
        `    structuredOutput: ${features.includes('structured_outputs')},\n` +
        `    vision: ${(m.architecture?.modality ?? '').includes('image->')},\n` +
        `    region: '${region}',\n` +
        `  },`
      );
    })
    .join('\n');

  return `/**
 * What Nebius Token Factory serves, priced.
 *
 * GENERATED by \`scripts/nebius-catalog.ts\` from \`GET /v1/models?verbose=true\`
 * on ${on}. Do not edit by hand — rerun the script.
 *
 * Only models that declare \`tools\` are here. Every surface this runner offers is
 * a tool surface, so a model that cannot call one cannot run a task at all, and
 * listing it would only let a research fail later instead of at load.
 *
 * \`region\` is Nebius's own, and is the data-residency answer for anyone who has
 * to give one: a payments research that may not leave the UK should read it
 * before choosing a model, not after.
 */
export interface NebiusModel {
  /** The id Nebius answers to, vendor half included: \`moonshotai/Kimi-K3\`. */
  id: string;
  inputPerMTok: number;
  outputPerMTok: number;
  contextWindow: number;
  reasoning: boolean;
  structuredOutput: boolean;
  vision: boolean;
  /** Where it runs, e.g. \`uk-south1 (UK)\`. Empty when Nebius named none. */
  region: string;
}

/** The date the table was pulled. Prices move; this says how stale ours may be. */
export const NEBIUS_GENERATED_ON = '${on}';

export const NEBIUS_MODELS: readonly NebiusModel[] = [
${rows}
];
`;
}

const key = (await resolveKey(NEBIUS)).value;
if (key === null) {
  console.error(`no ${NEBIUS} key. Try: excruciate keys set ${NEBIUS}`);
  process.exit(1);
}

const res = await fetch(`${NEBIUS_BASE_URL}/v1/models?verbose=true`, {
  headers: { Authorization: `Bearer ${key}` },
});
if (!res.ok) {
  console.error(`GET /v1/models?verbose=true → ${res.status} ${await res.text()}`);
  process.exit(1);
}

const body = (await res.json()) as { data?: Verbose[] };
const all = body.data ?? [];
const tooled = all
  .filter((m) => (m.supported_features ?? []).includes('tools'))
  .sort((a, b) => String(a.id).localeCompare(String(b.id)));

if (tooled.length === 0) {
  // Refusing to write an empty table is the whole point of checking: a listing
  // outage would otherwise silently delete every Nebius model from the catalog.
  console.error(`${all.length} models returned, none declaring tools — refusing to write an empty table.`);
  process.exit(1);
}

const on = new Date().toISOString().slice(0, 10);
const next = render(tooled, on);

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  // The date line always differs, so it is not what is compared.
  const strip = (s: string): string => s.replace(/^export const NEBIUS_GENERATED_ON = '.*';$/m, '');
  if (strip(current) === strip(next)) {
    console.log(`up to date — ${tooled.length} tool-capable models of ${all.length}`);
    process.exit(0);
  }
  console.error('src/nebius-models.ts is out of date. Run: bun run scripts/nebius-catalog.ts');
  process.exit(1);
}

writeFileSync(OUT, next);
console.log(`wrote ${OUT} — ${tooled.length} tool-capable models of ${all.length} served`);
