/**
 * What Nebius Token Factory serves, priced.
 *
 * GENERATED by `scripts/nebius-catalog.ts` from `GET /v1/models?verbose=true`
 * on 2026-08-24. Do not edit by hand — rerun the script.
 *
 * Only models that declare `tools` are here. Every surface this runner offers is
 * a tool surface, so a model that cannot call one cannot run a task at all, and
 * listing it would only let a research fail later instead of at load.
 *
 * `region` is Nebius's own, and is the data-residency answer for anyone who has
 * to give one: a payments research that may not leave the UK should read it
 * before choosing a model, not after.
 */
export interface NebiusModel {
  /** The id Nebius answers to, vendor half included: `moonshotai/Kimi-K3`. */
  id: string;
  inputPerMTok: number;
  outputPerMTok: number;
  contextWindow: number;
  reasoning: boolean;
  structuredOutput: boolean;
  vision: boolean;
  /** Where it runs, e.g. `uk-south1 (UK)`. Empty when Nebius named none. */
  region: string;
}

/** The date the table was pulled. Prices move; this says how stale ours may be. */
export const NEBIUS_GENERATED_ON = '2026-08-24';

export const NEBIUS_MODELS: readonly NebiusModel[] = [
  {
    id: 'deepseek-ai/DeepSeek-V4-Flash',
    inputPerMTok: 0.14,
    outputPerMTok: 0.28,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'deepseek-ai/DeepSeek-V4-Flash-0731',
    inputPerMTok: 0.14,
    outputPerMTok: 0.28,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'deepseek-ai/DeepSeek-V4-Pro',
    inputPerMTok: 1.75,
    outputPerMTok: 3.5,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'uk-south1 (UK)',
  },
  {
    id: 'google/gemma-3-27b-it',
    inputPerMTok: 0.1,
    outputPerMTok: 0.3,
    contextWindow: 110000,
    reasoning: false,
    structuredOutput: false,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct',
    inputPerMTok: 0.13,
    outputPerMTok: 0.4,
    contextWindow: 131072,
    reasoning: false,
    structuredOutput: false,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'MiniMaxAI/MiniMax-M2.5',
    inputPerMTok: 0.3,
    outputPerMTok: 1.2,
    contextWindow: 196608,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'MiniMaxAI/MiniMax-M3',
    inputPerMTok: 0.3,
    outputPerMTok: 1.2,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'moonshotai/Kimi-K2.6',
    inputPerMTok: 0.95,
    outputPerMTok: 4,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: true,
    region: 'us-central1 (US)',
  },
  {
    id: 'moonshotai/Kimi-K2.7-Code',
    inputPerMTok: 0.95,
    outputPerMTok: 4,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'moonshotai/Kimi-K3',
    inputPerMTok: 3,
    outputPerMTok: 15,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: false,
    vision: true,
    region: 'eu-west2 (FR)',
  },
  {
    id: 'NousResearch/Hermes-4-405B',
    inputPerMTok: 1,
    outputPerMTok: 3,
    contextWindow: 131072,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'NousResearch/Hermes-4-70B',
    inputPerMTok: 0.13,
    outputPerMTok: 0.4,
    contextWindow: 131072,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'nvidia/Cosmos3-Super-Reasoner',
    inputPerMTok: 0.1,
    outputPerMTok: 0.3,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: true,
    vision: true,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'nvidia/Nemotron-3_5-Lightning',
    inputPerMTok: 0.06,
    outputPerMTok: 0.24,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'nvidia/Nemotron-3-Nano-Omni',
    inputPerMTok: 0.06,
    outputPerMTok: 0.24,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'nvidia/nemotron-3-super-120b-a12b',
    inputPerMTok: 0.3,
    outputPerMTok: 0.9,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'nvidia/Nemotron-3-Ultra-550b-a55b',
    inputPerMTok: 1,
    outputPerMTok: 3,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B',
    inputPerMTok: 0.06,
    outputPerMTok: 0.24,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'openai/gpt-oss-120b',
    inputPerMTok: 0.15,
    outputPerMTok: 0.6,
    contextWindow: 131072,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    inputPerMTok: 0.2,
    outputPerMTok: 0.6,
    contextWindow: 262144,
    reasoning: false,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    inputPerMTok: 0.1,
    outputPerMTok: 0.3,
    contextWindow: 262144,
    reasoning: false,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'Qwen/Qwen3-32B',
    inputPerMTok: 0.1,
    outputPerMTok: 0.3,
    contextWindow: 40960,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'Qwen/Qwen3-Next-80B-A3B-Thinking',
    inputPerMTok: 0.15,
    outputPerMTok: 1.2,
    contextWindow: 128000,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'Qwen/Qwen3.5-397B-A17B',
    inputPerMTok: 0.6,
    outputPerMTok: 3.6,
    contextWindow: 262144,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'us-central1 (US)',
  },
  {
    id: 'zai-org/GLM-5.1',
    inputPerMTok: 1.4,
    outputPerMTok: 4.4,
    contextWindow: 202752,
    reasoning: true,
    structuredOutput: true,
    vision: false,
    region: 'eu-north1 (FI)',
  },
  {
    id: 'zai-org/GLM-5.2',
    inputPerMTok: 1.4,
    outputPerMTok: 4.4,
    contextWindow: 1048576,
    reasoning: true,
    structuredOutput: false,
    vision: false,
    region: 'uk-south1 (UK)',
  },
];
